### ISSUE TITLE
Websocket Auth prevents any other Events from being sent

### ISSUE THREAD

**Issue by onelapahead** [openathena/server#41]
- With my branch `team-lobby` on the web client I have some janky forms for creating teams, authenticating as a team member, and starting the game (still have a lot of cleaning up to do, and then routing)
- If I authenticate as a team member, I receive an additional `TEAM_CREATED` event -- is that intentional?
- Could there instead be some like an `AUTH_SUCCESSFUL` or `AUTH_FAILED` event sent on the socket? The successful event would only be visible to members of that team, and these would just be used to help create success and failure messages when trying to auth

**Comment by fuchsnj** [comment]
Currently you should receive a reset, and then it sends all events again, since the authentication changed. You probably didn't implement reset yet so it looks like a duplicate team created event.

We don't need an auth failed event since it will disconnect the websocket with an error message.
